baseURL = "/"
languageCode = "en-gb"
title = "Campaigns Made Easy"
theme = "kube"

description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = cme
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Docs"
    weight = 10
    url = "/docs/"
[[menu.main]]
    name = "Demo"
    weight = 20
    url = "http://demo.campaignsmadeeasy.com"

